[project]
name = "product-service"
version = "0.1.0"
description = "Service for CRUD products"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.30.0",
    "fastapi[standard]>=0.119.1",
    "pika>=1.3.2",
    "sqlalchemy>=2.0.44",
]
