[project]
name = "cart-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.120.1",
    "faststream[rabbit]>=0.6.2",
    "redis[asyncio]>=7.0.1",
]
